
    \begin{center}
        \linespread{1.3}
        \zihao{-3}\bfseries
        \vspace*{10pt}

        {\sound@value@ch@title}

        \vspace*{20pt}

        {\zihao{1}\bfseries\sffamily \sound@value@ch@subtitle}
        
        \vspace*{195pt}
        {%
            \sound@label@ch@projectname：\ulenhance{\ulextend{\sound@value@ch@projectname}}
            \sound@label@ch@manager：\ulenhance{\ulextend{\sound@value@ch@manager}}
            \sound@label@ch@department：\ulenhance{\ulextend{\sound@value@ch@department}}
            \sound@label@ch@applydate：\ulenhance{\ulextend{\sound@value@ch@applydate}}
        }
        
        \vspace*{50pt}
        {\sound@value@ch@company}

    \end{center}